const PHOTO_COUNT = 25;
const START_ID = 0;
const HASHTAG_VALIDATION_ERROR_MESSAGE = 'ХешТег введен неверно';
const DESCRIPTION_LENGTH_ERROR_MESSAGE = 'Максимальная длина 140 символов';
const MAX_HASHTAG_COUNT = 5;
const ZOOM_MAX = 100;
const ZOOM_MIN = 25;
const ZOOM_STEP = 25;
const DESCRIPTION_LENGTH_FIELD = 140;
const REDUCE_ZOOM_BUTTON_CLASS = '.scale__control--smaller';
const INCREASE_ZOOM_BUTTON_CLASS  = '.scale__control--bigger';
const HASHTAG_MASK = /^#[A-Za-zА-Яа-яЁё0-9]{1,19}$/;

export {HASHTAG_MASK, INCREASE_ZOOM_BUTTON_CLASS, REDUCE_ZOOM_BUTTON_CLASS, PHOTO_COUNT, START_ID, HASHTAG_VALIDATION_ERROR_MESSAGE, DESCRIPTION_LENGTH_ERROR_MESSAGE, MAX_HASHTAG_COUNT, ZOOM_MAX, ZOOM_MIN, ZOOM_STEP, DESCRIPTION_LENGTH_FIELD};
