const PHOTO_COUNT = 25;
const START_ID = 0;
const ERROR_MESSAGE = { HASHTAG_VALIDATION: 'ХешТег введен неверно', DESCRIPTION_LENGTH: 'Максимальная длина 140 символов' };
const MAX_HASHTAG_COUNT = 5;
const ZOOM = { MAX: 100, MIN: 25, STEP: 25 };
const DESCRIPTION_LENGTH_FIELD = 140;
const ZOOM_CONTROL_BUTTON_CLASS = { REDUCE: '.scale__control--smaller', INCREASE: '.scale__control--bigger' };
const HASHTAG_MASK = /^#[A-Za-zА-Яа-яЁё0-9]{1,19}$/;
const ONE_TIME_BIG_PICTURE_COMMENTS = 5;

export {ONE_TIME_BIG_PICTURE_COMMENTS, HASHTAG_MASK, ZOOM_CONTROL_BUTTON_CLASS, PHOTO_COUNT, START_ID, ERROR_MESSAGE, MAX_HASHTAG_COUNT, ZOOM, DESCRIPTION_LENGTH_FIELD};
